#!/bin/bash

# Older CUDA Systems
# docker run --rm -u $(id -u):$(id -g) -v $(pwd):/home/translator -it --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 griffith/mwp-automatic-solver bash

if [ -d '/proc/driver/nvidia' ]; then
    # Edit --gpus device value to the GPUs you want to use.
    # For multiple use '"device=0,1,...,n"' for n GPUs
    docker run --rm -u $(id -u):$(id -g) -v $(pwd):/home/translator --gpus device=0 -it griffith/mwp-automatic-solver bash
    else
    docker run --rm -u $(id -u):$(id -g) -v $(pwd):/home/translator -it griffith/mwp-automatic-solver bash
fi
